# Generated by Django 3.0 on 2019-12-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('manufucturer', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('drug_verification', models.BooleanField(default=False)),
                ('drug_registerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_registerer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
