# Generated by Django 3.0 on 2019-12-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pharmacy_id', models.CharField(blank=True, max_length=100)),
                ('pharmacist', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufucturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufucturer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('manufucturer', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('drug_verification', models.BooleanField(default=False)),
                ('drug_registerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_registerer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
