# Generated by Django 3.0 on 2019-12-11 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_id',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
