# Generated by Django 3.0 on 2019-12-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20191211_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_id',
            field=models.CharField(blank=True, default='<funct', max_length=100, unique=True),
        ),
    ]
