# Generated by Django 3.0 on 2019-12-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_pharmacy_drugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='drugs',
            field=models.ManyToManyField(null=True, to='drugs.Drugs'),
        ),
    ]
