# Generated by Django 3.0 on 2019-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20191211_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_id',
            field=models.CharField(blank=True, default='a43127', max_length=100, unique=True),
        ),
    ]
