# Generated by Django 3.0 on 2019-12-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20191214_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='drugs',
            field=models.ManyToManyField(blank=True, to='drugs.Drugs'),
        ),
    ]
