# Generated by Django 3.0 on 2019-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20191211_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
